# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqQbQL1tnXfz-mETIHQjMmBVN4g7chSO
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from io import StringIO


data = """
order_id,customer_id,product_id,quantity,unit_price,discount,order_date
1,1,1,1,45000,0,2023-01-10
2,2,2,1,79990,5,2023-01-15
3,3,3,1,65990,0,2023-02-20
4,4,4,1,3490,0,2023-03-10
5,5,5,1,5990,10,2023-03-15
6,6,6,1,3990,0,2023-03-18
7,7,7,1,29990,15,2023-04-05
8,8,8,1,42990,5,2023-04-10
9,9,9,1,54990,0,2023-04-15
10,10,10,1,8990,0,2023-04-20
"""

products_data = """
product_id,product_name,category_id,price
1,Ноутбук ASUS X543,2,45000
2,Смартфон Samsung Galaxy S21,3,79990
3,Холодильник Bosch KGN39,5,65990
4,Фен Rowenta CV7110,6,3490
5,Джинсы мужские Levi's 511,8,5990
6,Платье женское Zara,9,3990
7,Наушники Sony WH-1000XM4,1,29990
8,Стиральная машина LG F2J6,5,42990
9,Кофемашина DeLonghi ECAM,6,54990
10,Рюкзак Herschel Little America,10,8990
"""

orders = pd.read_csv(StringIO(data))
products = pd.read_csv(StringIO(products_data))

merged_data = pd.merge(orders, products, on='product_id')
merged_data['total_sale'] = merged_data['quantity'] * merged_data['unit_price'] * (1 - merged_data['discount']/100)

top_products = merged_data.groupby('product_name')['total_sale'].sum().sort_values(ascending=False).head(5)

plt.figure(figsize=(10, 6))
sns.barplot(x=top_products.values, y=top_products.index, palette='viridis')
plt.title('Топ-5 товаров по выручке')
plt.xlabel('Общая выручка (руб)')
plt.ylabel('Товар')
plt.show()

from google.colab import drive
drive.mount('/content/drive')